/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForWhoRouteImport } from './routes/for-who'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedTrajectoireRouteImport } from './routes/_authenticated/trajectoire'
import { Route as AuthenticatedSolverRouteImport } from './routes/_authenticated/solver'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedOracleRouteImport } from './routes/_authenticated/oracle'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedMindmapsRouteImport } from './routes/_authenticated/mindmaps'
import { Route as AuthenticatedMemoireRouteImport } from './routes/_authenticated/memoire'
import { Route as AuthenticatedForgeRouteImport } from './routes/_authenticated/forge'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedCodexRouteImport } from './routes/_authenticated/codex'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSolverIdRouteImport } from './routes/_authenticated/solver.$id'
import { Route as AuthenticatedSessionIdRouteImport } from './routes/_authenticated/session.$id'
import { Route as AuthenticatedMindmapsIdRouteImport } from './routes/_authenticated/mindmaps.$id'
import { Route as AuthenticatedExamsIdRouteImport } from './routes/_authenticated/exams.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForWhoRoute = ForWhoRouteImport.update({
  id: '/for-who',
  path: '/for-who',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrajectoireRoute =
  AuthenticatedTrajectoireRouteImport.update({
    id: '/trajectoire',
    path: '/trajectoire',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSolverRoute = AuthenticatedSolverRouteImport.update({
  id: '/solver',
  path: '/solver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOracleRoute = AuthenticatedOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMindmapsRoute = AuthenticatedMindmapsRouteImport.update({
  id: '/mindmaps',
  path: '/mindmaps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemoireRoute = AuthenticatedMemoireRouteImport.update({
  id: '/memoire',
  path: '/memoire',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForgeRoute = AuthenticatedForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodexRoute = AuthenticatedCodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolverIdRoute = AuthenticatedSolverIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSolverRoute,
} as any)
const AuthenticatedSessionIdRoute = AuthenticatedSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMindmapsIdRoute = AuthenticatedMindmapsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMindmapsRoute,
} as any)
const AuthenticatedExamsIdRoute = AuthenticatedExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedExamsRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/for-who': typeof ForWhoRoute
  '/onboarding': typeof OnboardingRoute
  '/subjects': typeof SubjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/codex': typeof AuthenticatedCodexRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/forge': typeof AuthenticatedForgeRoute
  '/memoire': typeof AuthenticatedMemoireRoute
  '/mindmaps': typeof AuthenticatedMindmapsRouteWithChildren
  '/new': typeof AuthenticatedNewRoute
  '/oracle': typeof AuthenticatedOracleRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/solver': typeof AuthenticatedSolverRouteWithChildren
  '/trajectoire': typeof AuthenticatedTrajectoireRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/exams/$id': typeof AuthenticatedExamsIdRoute
  '/mindmaps/$id': typeof AuthenticatedMindmapsIdRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/solver/$id': typeof AuthenticatedSolverIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/for-who': typeof ForWhoRoute
  '/onboarding': typeof OnboardingRoute
  '/subjects': typeof SubjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/codex': typeof AuthenticatedCodexRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/forge': typeof AuthenticatedForgeRoute
  '/memoire': typeof AuthenticatedMemoireRoute
  '/mindmaps': typeof AuthenticatedMindmapsRouteWithChildren
  '/new': typeof AuthenticatedNewRoute
  '/oracle': typeof AuthenticatedOracleRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/solver': typeof AuthenticatedSolverRouteWithChildren
  '/trajectoire': typeof AuthenticatedTrajectoireRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/exams/$id': typeof AuthenticatedExamsIdRoute
  '/mindmaps/$id': typeof AuthenticatedMindmapsIdRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/solver/$id': typeof AuthenticatedSolverIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRoute
  '/for-who': typeof ForWhoRoute
  '/onboarding': typeof OnboardingRoute
  '/subjects': typeof SubjectsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/codex': typeof AuthenticatedCodexRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/_authenticated/forge': typeof AuthenticatedForgeRoute
  '/_authenticated/memoire': typeof AuthenticatedMemoireRoute
  '/_authenticated/mindmaps': typeof AuthenticatedMindmapsRouteWithChildren
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/oracle': typeof AuthenticatedOracleRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/solver': typeof AuthenticatedSolverRouteWithChildren
  '/_authenticated/trajectoire': typeof AuthenticatedTrajectoireRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/exams/$id': typeof AuthenticatedExamsIdRoute
  '/_authenticated/mindmaps/$id': typeof AuthenticatedMindmapsIdRoute
  '/_authenticated/session/$id': typeof AuthenticatedSessionIdRoute
  '/_authenticated/solver/$id': typeof AuthenticatedSolverIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/features'
    | '/for-who'
    | '/onboarding'
    | '/subjects'
    | '/admin'
    | '/app'
    | '/codex'
    | '/exams'
    | '/forge'
    | '/memoire'
    | '/mindmaps'
    | '/new'
    | '/oracle'
    | '/pricing'
    | '/profile'
    | '/settings'
    | '/solver'
    | '/trajectoire'
    | '/checkout/return'
    | '/exams/$id'
    | '/mindmaps/$id'
    | '/session/$id'
    | '/solver/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/features'
    | '/for-who'
    | '/onboarding'
    | '/subjects'
    | '/admin'
    | '/app'
    | '/codex'
    | '/exams'
    | '/forge'
    | '/memoire'
    | '/mindmaps'
    | '/new'
    | '/oracle'
    | '/pricing'
    | '/profile'
    | '/settings'
    | '/solver'
    | '/trajectoire'
    | '/checkout/return'
    | '/exams/$id'
    | '/mindmaps/$id'
    | '/session/$id'
    | '/solver/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/features'
    | '/for-who'
    | '/onboarding'
    | '/subjects'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/codex'
    | '/_authenticated/exams'
    | '/_authenticated/forge'
    | '/_authenticated/memoire'
    | '/_authenticated/mindmaps'
    | '/_authenticated/new'
    | '/_authenticated/oracle'
    | '/_authenticated/pricing'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/solver'
    | '/_authenticated/trajectoire'
    | '/checkout/return'
    | '/_authenticated/exams/$id'
    | '/_authenticated/mindmaps/$id'
    | '/_authenticated/session/$id'
    | '/_authenticated/solver/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRoute
  ForWhoRoute: typeof ForWhoRoute
  OnboardingRoute: typeof OnboardingRoute
  SubjectsRoute: typeof SubjectsRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-who': {
      id: '/for-who'
      path: '/for-who'
      fullPath: '/for-who'
      preLoaderRoute: typeof ForWhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trajectoire': {
      id: '/_authenticated/trajectoire'
      path: '/trajectoire'
      fullPath: '/trajectoire'
      preLoaderRoute: typeof AuthenticatedTrajectoireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solver': {
      id: '/_authenticated/solver'
      path: '/solver'
      fullPath: '/solver'
      preLoaderRoute: typeof AuthenticatedSolverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/oracle': {
      id: '/_authenticated/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof AuthenticatedOracleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mindmaps': {
      id: '/_authenticated/mindmaps'
      path: '/mindmaps'
      fullPath: '/mindmaps'
      preLoaderRoute: typeof AuthenticatedMindmapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/memoire': {
      id: '/_authenticated/memoire'
      path: '/memoire'
      fullPath: '/memoire'
      preLoaderRoute: typeof AuthenticatedMemoireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forge': {
      id: '/_authenticated/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof AuthenticatedForgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codex': {
      id: '/_authenticated/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof AuthenticatedCodexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solver/$id': {
      id: '/_authenticated/solver/$id'
      path: '/$id'
      fullPath: '/solver/$id'
      preLoaderRoute: typeof AuthenticatedSolverIdRouteImport
      parentRoute: typeof AuthenticatedSolverRoute
    }
    '/_authenticated/session/$id': {
      id: '/_authenticated/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AuthenticatedSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mindmaps/$id': {
      id: '/_authenticated/mindmaps/$id'
      path: '/$id'
      fullPath: '/mindmaps/$id'
      preLoaderRoute: typeof AuthenticatedMindmapsIdRouteImport
      parentRoute: typeof AuthenticatedMindmapsRoute
    }
    '/_authenticated/exams/$id': {
      id: '/_authenticated/exams/$id'
      path: '/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof AuthenticatedExamsIdRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsIdRoute: typeof AuthenticatedExamsIdRoute
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsIdRoute: AuthenticatedExamsIdRoute,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedMindmapsRouteChildren {
  AuthenticatedMindmapsIdRoute: typeof AuthenticatedMindmapsIdRoute
}

const AuthenticatedMindmapsRouteChildren: AuthenticatedMindmapsRouteChildren = {
  AuthenticatedMindmapsIdRoute: AuthenticatedMindmapsIdRoute,
}

const AuthenticatedMindmapsRouteWithChildren =
  AuthenticatedMindmapsRoute._addFileChildren(
    AuthenticatedMindmapsRouteChildren,
  )

interface AuthenticatedSolverRouteChildren {
  AuthenticatedSolverIdRoute: typeof AuthenticatedSolverIdRoute
}

const AuthenticatedSolverRouteChildren: AuthenticatedSolverRouteChildren = {
  AuthenticatedSolverIdRoute: AuthenticatedSolverIdRoute,
}

const AuthenticatedSolverRouteWithChildren =
  AuthenticatedSolverRoute._addFileChildren(AuthenticatedSolverRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCodexRoute: typeof AuthenticatedCodexRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedForgeRoute: typeof AuthenticatedForgeRoute
  AuthenticatedMemoireRoute: typeof AuthenticatedMemoireRoute
  AuthenticatedMindmapsRoute: typeof AuthenticatedMindmapsRouteWithChildren
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedOracleRoute: typeof AuthenticatedOracleRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSolverRoute: typeof AuthenticatedSolverRouteWithChildren
  AuthenticatedTrajectoireRoute: typeof AuthenticatedTrajectoireRoute
  AuthenticatedSessionIdRoute: typeof AuthenticatedSessionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCodexRoute: AuthenticatedCodexRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedForgeRoute: AuthenticatedForgeRoute,
  AuthenticatedMemoireRoute: AuthenticatedMemoireRoute,
  AuthenticatedMindmapsRoute: AuthenticatedMindmapsRouteWithChildren,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedOracleRoute: AuthenticatedOracleRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSolverRoute: AuthenticatedSolverRouteWithChildren,
  AuthenticatedTrajectoireRoute: AuthenticatedTrajectoireRoute,
  AuthenticatedSessionIdRoute: AuthenticatedSessionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRoute,
  ForWhoRoute: ForWhoRoute,
  OnboardingRoute: OnboardingRoute,
  SubjectsRoute: SubjectsRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
